//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrolment
    {
        public int RequestID { get; set; }
        public int UserRef_ID { get; set; }
        public int CourseRef_ID { get; set; }
        public string Date { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
