//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GPAEntities : DbContext
    {
        public GPAEntities()
            : base("name=GPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseEnrolment> CourseEnrolments { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CourseUser> CourseUsers { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleTask> RoleTasks { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<StudentGrade> StudentGrades { get; set; }
    
        public virtual ObjectResult<GetEcourses_Result> GetEcourses(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEcourses_Result>("GetEcourses", userIDParameter);
        }
    
        public virtual ObjectResult<FindGPA_Result1> FindGPA(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindGPA_Result1>("FindGPA", userIDParameter);
        }
    }
}
